import './globals.css';
import type { Metadata } from 'next';
import { getCustomeCode } from './lib/contentful-customCode';
import { isEmpty } from './helper/helper';
import parse from 'html-react-parser';

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app'
};

async function getcontent() {
  return await getCustomeCode();
}

export default async function RootLayout({ children }: { children: React.ReactNode }) {
  const data = await getcontent();
  const header = data?.filter((item: { name: string }) => item?.name === 'Head')?.[0] ?? null;
  const afterBody = data?.filter((item: { name: string }) => item?.name === 'After Body Tag Start')?.[0] ?? null;
  const beforeBody = data?.filter((item: { name: string }) => item?.name === 'Before Body Tag Close')?.[0] ?? null;
  const newData = { header, afterBody, beforeBody };

  return (
    <html lang='en'>
      <head>
        {!isEmpty(newData?.header?.code) && process.env.NODE_ENV === 'production' && parse(newData?.header?.code)}
      </head>
      <body>
        {!isEmpty(newData?.afterBody?.code) && process.env.NODE_ENV === 'production' && parse(newData?.afterBody?.code)}
        {children}
        {!isEmpty(newData?.beforeBody?.code) &&
          process.env.NODE_ENV === 'production' &&
          parse(newData?.beforeBody?.code)}
      </body>
    </html>
  );
}
