import './globals.css';
import type { Metadata } from 'next';
import { getCustomeCode } from './lib/contentful-customCode';
import { isEmpty } from './helper/helper';
import parse from 'html-react-parser';

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app'
};

async function getcontent() {
  return await getCustomeCode();
}

export default async function RootLayout({ children }: { children: React.ReactNode }) {
  const data = await getcontent();
  const header = data?.find((item: { name: string }) => item?.name === 'Head');
  const afterBody = data?.find((item: { name: string }) => item?.name === 'After Body Tag Start');
  const beforeBody = data?.find((item: { name: string }) => item?.name === 'Before Body Tag Close');
  const newData = { header, afterBody, beforeBody };

  return (
    <>
      <html lang='en'>
        <head>{!isEmpty(newData?.header?.code) && parse(newData?.header?.code)}</head>
        <body>
          {!isEmpty(newData?.afterBody?.code) && parse(newData?.afterBody?.code)}
          {children}
          {!isEmpty(newData?.beforeBody?.code) && parse(newData?.beforeBody?.code)}
        </body>
      </html>
    </>
  );
}
